### PR TITLE
J5 Inventor's Kit Campaign

### PR DESCRIPTION
**Pull request by isaacdurazo**
Hey @ajpiano, @reconbot, @rwaldron, @jorydotcom Here's the implementation of the the Inventor's kit campaign. Please let me know what you think

### CODE REVIEW

**Comment by ajpiano** [comment]
We need to have this link somewhere; @reconbot can you let us know where that is?

I would like to hear from @reconbot and @rwaldron as to whether this should replace the existing header entirely or if we should create a "mini" header that says the "The JavaScript Robotics & IoT Platform"

**Comment by ajpiano** [comment]
I found a way to add a minimal header above the hero image - it just has "The JavaScript Robotics & IoT Programming Framework" with no platform changes or johnny-five image. Is that copy acceptable?

I made the whole banner link to the product page for the j5ik on sparkfun, as it is easier than only making the button in the last frame of the gif into a link...thoughts?

**Comment by ajpiano** [comment]
This is ready for review now @reconbot

**Comment by ajpiano** [comment]
I think your feedback makes sense and I like the idea of adding the section after the description and giving a few words of context and having a static CTA. I'll work on trying to break these sections apart

**Comment by rwaldron** [comment]
Please make sure you all test these layout changes across every possible device/media that you can. Presently, the site looks totally awesome on every device—and only because we spent a lot of time make sure of it.

**Comment by ajpiano** [comment]
After conferring with @reconbot I broke this hero section into its own area before the hello world, and also moved the mailing list CTA to the footer of all pages, rather than above the header only on the home page.

The layout needs some finessing from @isaacdurazo 

The copy in this section is not final yet but represents the fundamental thrust of what @reconbot and I discussed.

@rwaldron we will take care to make sure this displays properly across devices; at the moment it does not

**Comment by ajpiano** [comment]
Current state of affairs

**Comment by ajpiano** [comment]
With @isaacdurazo's latest changes the design for this is ready for review I would like to spend some time working on the copy with @reconbot and @jorydotcom before calling it final

**Comment by Resseguie** [comment]
Looking good!

@reconbot Just a related note. In the "wishlist" you created on sparkfun for the full sumobot, the recommended battery pack is retired. You'll likely want to update that before this change goes live.
https://www.sparkfun.com/wish_lists/125260

**Pull request closed without merging**
